### ISSUE TITLE
Broadcast doesn't stop once you take your finger off the Voice Command Activation Button

### ISSUE THREAD

**Issue by NilaierMusic** [Judiks/VoiceShipControl#5]
Simple as that, once i press the `Voice Command Activation Button` the voice broadcast starts:
```cs
[Info   :   Console] Broadcasting started
```
But when i release the held button, broadcast doesn't stop or stops improperly and, obviously, no resulted text from recognition is being displayed in the console.

Not sure why or for what reason, but if i had to make a guess, might be due to a change in how ending the broadcast works in 1.0.2.
In the new code, it just [destroys the instance](https://github.com/Judiks/VoiceShipControl/commit/49c8ea3c55665e2c3a742d7ffadb210e7b7b3143?diff=unified&w=0#diff-c89bb4d4d7b984854c8cc3f03f5b99880c9429d135e160762725fc903a26c470R88), so it 'maybe' doesn't go through the process of finishing the recognition and terminates its work early.

Or i might be completely wrong in this regard. Can't say for sure!

**Comment by Judiks** [comment]
@NilaierMusic let me guess it's happened not always and on small phrases like 'M6' for door inside the dange opening? I saw it might be spoken phrase is to small for recording or you start speak in same time like button was pressed and because of some delay microphone not start recording. 
Not sure if i can fix this delay will check later. In other cases with longer phrase all works fine?

Destroy logic not related for this issue because it's was made to prevent process stuck after game closed. And it's fired just in case when game is closed or user quit to menu. Also tanks to this feature now you can change language in main menu and not totally exit the game.

**Comment by NilaierMusic** [comment]
No, this was happening with medium sentences like `buy flashlight` or `route to the company building,` but now, weirdly, this is resolved. I will reopen it once i encounter this issue and figure out the cause, but, for now, i think we can close it.
